api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            app_id:
                name: 'X-APP-ID'
                type: header
            app_secret:
                name: 'X-APP-SECRET'
                type: header
                

    exception_to_status:
        App\Exceptions\InvalidRequestParamsException: 400
