doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            App\Enum\DayOfWeek: Doctrine\DBAL\Types\StringType
            App\Enum\ReservationStatus: Doctrine\DBAL\Types\StringType
            App\Enum\DynamicPropertyType: Doctrine\DBAL\Types\StringType
            App\Enum\OfferStatus: Doctrine\DBAL\Types\StringType
            App\Enum\OfferCommentStatus: Doctrine\DBAL\Types\StringType
        
        mapping_types:
            App\Enum\DayOfWeek: string
            App\Enum\ReservationStatus: string
            App\Enum\DynamicPropertyType: string
            App\Enum\OfferStatus: string
            App\Enum\OfferCommentStatus: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
